In [1]:
import numpy as np

In [2]:
y = np.array([1, 2, 3, 2, 3, 1, 1, 4, 4, 1, 4, 2]).reshape(-1,1)

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
one = OneHotEncoder()

In [5]:
y_new = one.fit_transform(y).toarray()

In [6]:
y_new

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [7]:
y_new[:,-1]

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.])

In [8]:
pk = np.sum(y_new, axis=0) / len(y)

In [9]:
pk

array([0.33333333, 0.25      , 0.16666667, 0.25      ])

In [35]:
np.mean(y_new, axis=0)

array([0.33333333, 0.25      , 0.16666667, 0.25      ])

In [10]:
-np.sum(pk * np.log(pk))

1.3579778549873243

In [11]:
np.sum(pk*pk)

0.2638888888888889

In [12]:
pk

array([0.33333333, 0.25      , 0.16666667, 0.25      ])

In [13]:
np.std(pk)

0.05892556509887896

In [14]:
b = np.random.randint(10,size=(10,))

In [15]:
b

array([5, 0, 6, 6, 0, 5, 0, 9, 0, 5])

In [16]:
np.argpartition(b, 4)

array([1, 4, 8, 6, 0, 5, 3, 7, 2, 9])

In [17]:
b[np.argpartition(b, 4)]

array([0, 0, 0, 0, 5, 5, 6, 9, 6, 5])

In [18]:
b

array([5, 0, 6, 6, 0, 5, 0, 9, 0, 5])

In [19]:
np.where(b <= 5)[0]

array([0, 1, 4, 5, 6, 8, 9])

In [20]:
b[np.where(b <= 5)[0]]

array([5, 0, 0, 5, 0, 0, 5])

In [21]:
b[np.where(b > 5)[0]]

array([6, 6, 9])

In [22]:
~2

-3

In [23]:
y_new[0:3]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
b

array([5, 0, 6, 6, 0, 5, 0, 9, 0, 5])

In [25]:
i = b <= 5

In [26]:
i

array([ True,  True, False, False,  True,  True,  True, False,  True,
        True])

In [27]:
b[i]

array([5, 0, 0, 5, 0, 0, 5])

In [28]:
~False

-1

In [29]:
b[~i]

array([6, 6, 9])

In [30]:
~i

array([False, False,  True,  True, False, False, False,  True, False,
       False])

In [31]:
y_new.shape

(12, 4)

In [32]:
a = True

In [33]:
a

True

In [34]:
~np.array([a])

array([False])

In [37]:
y

array([[1],
       [2],
       [3],
       [2],
       [3],
       [1],
       [1],
       [4],
       [4],
       [1],
       [4],
       [2]])

In [38]:
y.shape

(12, 1)

In [39]:
np.mean(y_new, axis=0)

array([0.33333333, 0.25      , 0.16666667, 0.25      ])

In [40]:
np.mean(y, axis=0)

array([2.33333333])

In [41]:
np.mean(y)

2.3333333333333335

In [42]:
f = np.mean

In [43]:
f(y)

2.3333333333333335

In [44]:
b

array([5, 0, 6, 6, 0, 5, 0, 9, 0, 5])

In [45]:
np.bincount(b)

array([4, 0, 0, 0, 0, 3, 2, 0, 0, 1])

In [61]:
w = np.array([0.1, 0.2, 0.1, 0.3, 0.5, 0.3, 0.3, 0.3])

In [62]:
w

array([0.1, 0.2, 0.1, 0.3, 0.5, 0.3, 0.3, 0.3])

In [63]:
values, inverse, counts = np.unique(w, return_counts=True, return_inverse=True)

In [64]:
values

array([0.1, 0.2, 0.3, 0.5])

In [65]:
counts

array([2, 1, 4, 1])

In [66]:
inverse

array([0, 1, 0, 2, 3, 2, 2, 2])

In [67]:
values[inverse]

array([0.1, 0.2, 0.1, 0.3, 0.5, 0.3, 0.3, 0.3])

In [68]:
values, counts = np.unique(w, return_counts=True)

In [69]:
values

array([0.1, 0.2, 0.3, 0.5])

In [70]:
counts

array([2, 1, 4, 1])

In [71]:
counts.argmax()

2

In [72]:
values[counts.argmax()]

0.3

In [73]:
y_new

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [75]:
np.mean(y_new, axis=0).argmax()

0

In [76]:
'median' in 'mad_median'

True

In [81]:
def f(a, b):
    return a @ b

In [87]:
t = (np.array([[1,2,3]]), np.array([-1,-2,-3]))

In [88]:
f(*t)

array([-14])

In [89]:
def g(pred, ind):
    pred[ind] = -1

In [103]:
pred = np.array(10*[0]).reshape(-1, 1)
ind = np.array([1,5,7])

In [104]:
g(pred, ind)

In [105]:
pred

array([[ 0],
       [-1],
       [ 0],
       [ 0],
       [ 0],
       [-1],
       [ 0],
       [-1],
       [ 0],
       [ 0]])

In [100]:
def h(a,b,c,d,e):
    
    return a*b*c*d*e

In [101]:
t = (3,4)

In [102]:
h(1,2,*t,5)

120

In [128]:
c = np.zeros((4, 3))

In [129]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
ind

array([1, 5, 7])

In [131]:
c[0] = ind

In [132]:
c

array([[1., 5., 7.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
c[1:3] = 3*ind

In [134]:
c

array([[ 1.,  5.,  7.],
       [ 3., 15., 21.],
       [ 3., 15., 21.],
       [ 0.,  0.,  0.]])