In [171]:
import numpy as np

In [172]:
np.random.randn(5, 10).shape

(5, 10)

In [173]:
stdv = 0.05

In [174]:
np.random.uniform(-stdv, stdv, size = 4)

array([ 0.0227704 , -0.0147136 , -0.00347243, -0.02311267])

In [175]:
b = np.random.uniform(-stdv, stdv, size = (1,4))
b

array([[-0.01721437,  0.02476644,  0.00527479,  0.03106335]])

In [176]:
n_in = 3
n_out = 4

In [177]:
W = np.random.random((n_in, n_out))

In [178]:
W

array([[0.38996896, 0.97233183, 0.01546821, 0.8917501 ],
       [0.50621591, 0.13675787, 0.1936802 , 0.96697848],
       [0.15903151, 0.72364526, 0.23481487, 0.39399388]])

In [179]:
gradOutput = np.random.random((1, n_out))

In [180]:
gradOutput.dot(W.T)

array([[1.47502457, 1.07651214, 0.82325897]])

In [181]:
x_in = np.random.random((2, n_in))
x_in

array([[0.14191751, 0.89901323, 0.63824319],
       [0.75451624, 0.41798971, 0.534622  ]])

In [182]:
x_in[:, None, :]

array([[[0.14191751, 0.89901323, 0.63824319]],

       [[0.75451624, 0.41798971, 0.534622  ]]])

In [183]:
gradOutput

array([[0.17942448, 0.5872671 , 0.00551426, 0.93518443]])

In [184]:
gradOutput[:,:, None]

array([[[0.17942448],
        [0.5872671 ],
        [0.00551426],
        [0.93518443]]])

In [185]:
x_in[:, None, :] * gradOutput[:,:, None]

array([[[2.54634752e-02, 1.61304985e-01, 1.14516456e-01],
        [8.33434818e-02, 5.27960891e-01, 3.74819229e-01],
        [7.82569526e-04, 4.95738954e-03, 3.51943667e-03],
        [1.32719041e-01, 8.40743171e-01, 5.96875094e-01]],

       [[1.35378687e-01, 7.49975872e-02, 9.59242771e-02],
        [4.43102563e-01, 2.45471602e-01, 3.13965913e-01],
        [4.16059606e-03, 2.30490245e-03, 2.94804285e-03],
        [7.05611835e-01, 3.90897463e-01, 4.99970171e-01]]])

In [186]:
n_batch = 5

In [187]:
x_in = np.random.randint(0, 10, size=(n_batch, n_in))
x_in[:, None, :]

array([[[6, 0, 5]],

       [[5, 2, 9]],

       [[8, 1, 2]],

       [[8, 2, 5]],

       [[3, 7, 9]]])

In [188]:
x_in

array([[6, 0, 5],
       [5, 2, 9],
       [8, 1, 2],
       [8, 2, 5],
       [3, 7, 9]])

In [189]:
dx_out = np.random.randint(0, 10, size=(n_batch, n_out))
dx_out[:, :, None]

array([[[5],
        [4],
        [2],
        [9]],

       [[8],
        [3],
        [2],
        [7]],

       [[1],
        [3],
        [1],
        [3]],

       [[9],
        [4],
        [8],
        [8]],

       [[1],
        [6],
        [4],
        [0]]])

In [190]:
dx_out

array([[5, 4, 2, 9],
       [8, 3, 2, 7],
       [1, 3, 1, 3],
       [9, 4, 8, 8],
       [1, 6, 4, 0]])

for `n_batch` $> 1$, `np.outer` doesn't work as expected

In [191]:
np.outer(x_in, dx_out).T

array([[30,  0, 25, 25, 10, 45, 40,  5, 10, 40, 10, 25, 15, 35, 45],
       [24,  0, 20, 20,  8, 36, 32,  4,  8, 32,  8, 20, 12, 28, 36],
       [12,  0, 10, 10,  4, 18, 16,  2,  4, 16,  4, 10,  6, 14, 18],
       [54,  0, 45, 45, 18, 81, 72,  9, 18, 72, 18, 45, 27, 63, 81],
       [48,  0, 40, 40, 16, 72, 64,  8, 16, 64, 16, 40, 24, 56, 72],
       [18,  0, 15, 15,  6, 27, 24,  3,  6, 24,  6, 15,  9, 21, 27],
       [12,  0, 10, 10,  4, 18, 16,  2,  4, 16,  4, 10,  6, 14, 18],
       [42,  0, 35, 35, 14, 63, 56,  7, 14, 56, 14, 35, 21, 49, 63],
       [ 6,  0,  5,  5,  2,  9,  8,  1,  2,  8,  2,  5,  3,  7,  9],
       [18,  0, 15, 15,  6, 27, 24,  3,  6, 24,  6, 15,  9, 21, 27],
       [ 6,  0,  5,  5,  2,  9,  8,  1,  2,  8,  2,  5,  3,  7,  9],
       [18,  0, 15, 15,  6, 27, 24,  3,  6, 24,  6, 15,  9, 21, 27],
       [54,  0, 45, 45, 18, 81, 72,  9, 18, 72, 18, 45, 27, 63, 81],
       [24,  0, 20, 20,  8, 36, 32,  4,  8, 32,  8, 20, 12, 28, 36],
       [48,  0, 40, 40, 16, 72, 64

In [192]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[30,  0, 25],
        [24,  0, 20],
        [12,  0, 10],
        [54,  0, 45]],

       [[40, 16, 72],
        [15,  6, 27],
        [10,  4, 18],
        [35, 14, 63]],

       [[ 8,  1,  2],
        [24,  3,  6],
        [ 8,  1,  2],
        [24,  3,  6]],

       [[72, 18, 45],
        [32,  8, 20],
        [64, 16, 40],
        [64, 16, 40]],

       [[ 3,  7,  9],
        [18, 42, 54],
        [12, 28, 36],
        [ 0,  0,  0]]])

In [193]:
result = x_in[:, None, :] * dx_out[:, :, None]
result

array([[[30,  0, 25],
        [24,  0, 20],
        [12,  0, 10],
        [54,  0, 45]],

       [[40, 16, 72],
        [15,  6, 27],
        [10,  4, 18],
        [35, 14, 63]],

       [[ 8,  1,  2],
        [24,  3,  6],
        [ 8,  1,  2],
        [24,  3,  6]],

       [[72, 18, 45],
        [32,  8, 20],
        [64, 16, 40],
        [64, 16, 40]],

       [[ 3,  7,  9],
        [18, 42, 54],
        [12, 28, 36],
        [ 0,  0,  0]]])

In [194]:
np.sum(result, axis=0)

array([[153,  42, 153],
       [113,  59, 127],
       [106,  49, 106],
       [177,  33, 154]])

In [195]:
dx_out

array([[5, 4, 2, 9],
       [8, 3, 2, 7],
       [1, 3, 1, 3],
       [9, 4, 8, 8],
       [1, 6, 4, 0]])

In [196]:
np.sum(dx_out, axis=0)

array([24, 20, 17, 27])

In [197]:
s = x_in[:, None, :]

In [198]:
s

array([[[6, 0, 5]],

       [[5, 2, 9]],

       [[8, 1, 2]],

       [[8, 2, 5]],

       [[3, 7, 9]]])

In [199]:
s.shape

(5, 1, 3)

In [200]:
x_in

array([[6, 0, 5],
       [5, 2, 9],
       [8, 1, 2],
       [8, 2, 5],
       [3, 7, 9]])

In [201]:
x_in.shape

(5, 3)

In [202]:
s.ndim

3

### =========

In [203]:
d = dx_out[:, :, None]
d

array([[[5],
        [4],
        [2],
        [9]],

       [[8],
        [3],
        [2],
        [7]],

       [[1],
        [3],
        [1],
        [3]],

       [[9],
        [4],
        [8],
        [8]],

       [[1],
        [6],
        [4],
        [0]]])

In [204]:
d.shape

(5, 4, 1)

In [205]:
dx_out

array([[5, 4, 2, 9],
       [8, 3, 2, 7],
       [1, 3, 1, 3],
       [9, 4, 8, 8],
       [1, 6, 4, 0]])

In [206]:
dx_out.shape

(5, 4)

In [207]:
np.arange(3, 10)[:, None]

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

A way to understand numpy array:

When dealing with $0$, $1$ or $2$ dimensional array, some of us try to give an interpretation through scalars, vectors and matrices. This is fine, since the definitions coincide but how od we picture and array of $(n, m, p)$ dimensions? 

- If `s` is a `(n, m)`-matrix and `d` is a `(n, q)`-matrix, then what does `s[:, None, :]` or `d[:,:, None]` mean? 
- Why does `s[:, None, :] * d[:,:, None]` work and what does it give?

One way of understanding this is, instead of looking at a $n$-dimensional array as an _array of elements_ we can look at it as an _array of arrays_.

- shape `(5, 4)`:
    - There are `5` rows. Each of those rows is an array of shape `(4,)`. That is and array of `4` elements.
    
    
- shape `(5, 1, 3)`:
    - There are `5` rows. Let's look at one of them. That row consists of a `(1, 3)` array. That is, in this row there is just `1` array of 3 elements.
    
    
- shape `(5, 4, 1)`: 
    - There are `5` rows. Let's look at one of them. That row consists of a `(4, 1)` array. That is, in this row there are `4` different arrays, each containing 1 element.

In [208]:
x_in[:, None, :]

array([[[6, 0, 5]],

       [[5, 2, 9]],

       [[8, 1, 2]],

       [[8, 2, 5]],

       [[3, 7, 9]]])

In [209]:
dx_out[:, :, None]

array([[[5],
        [4],
        [2],
        [9]],

       [[8],
        [3],
        [2],
        [7]],

       [[1],
        [3],
        [1],
        [3]],

       [[9],
        [4],
        [8],
        [8]],

       [[1],
        [6],
        [4],
        [0]]])

In [210]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[30,  0, 25],
        [24,  0, 20],
        [12,  0, 10],
        [54,  0, 45]],

       [[40, 16, 72],
        [15,  6, 27],
        [10,  4, 18],
        [35, 14, 63]],

       [[ 8,  1,  2],
        [24,  3,  6],
        [ 8,  1,  2],
        [24,  3,  6]],

       [[72, 18, 45],
        [32,  8, 20],
        [64, 16, 40],
        [64, 16, 40]],

       [[ 3,  7,  9],
        [18, 42, 54],
        [12, 28, 36],
        [ 0,  0,  0]]])

In [211]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[30,  0, 25],
        [24,  0, 20],
        [12,  0, 10],
        [54,  0, 45]],

       [[40, 16, 72],
        [15,  6, 27],
        [10,  4, 18],
        [35, 14, 63]],

       [[ 8,  1,  2],
        [24,  3,  6],
        [ 8,  1,  2],
        [24,  3,  6]],

       [[72, 18, 45],
        [32,  8, 20],
        [64, 16, 40],
        [64, 16, 40]],

       [[ 3,  7,  9],
        [18, 42, 54],
        [12, 28, 36],
        [ 0,  0,  0]]])

In [212]:
(dx_out[:, :, None] * x_in[:, None, :]).shape == (dx_out[:, :, None] * x_in[:, None, :]).shape

True

In [213]:
(dx_out[:, :, None] * x_in[:, None, :]).shape

(5, 4, 3)

In [214]:
(dx_out[:, :, None] * x_in[:, None, :]).shape

(5, 4, 3)

In [215]:
def log_smax(x_in):
    
    x_out = np.subtract(x_in, x_in.max(axis=1, keepdims=True))
    
    x_out = x_out - np.log(np.sum(np.exp(x_out), axis=1, keepdims=True))
    
    return x_out

In [216]:
x_in

array([[6, 0, 5],
       [5, 2, 9],
       [8, 1, 2],
       [8, 2, 5],
       [3, 7, 9]])

In [217]:
log_smax(x_in)

array([[-3.15072161e-01, -6.31507216e+00, -1.31507216e+00],
       [-4.01904501e+00, -7.01904501e+00, -1.90450079e-02],
       [-3.38489890e-03, -7.00338490e+00, -6.00338490e+00],
       [-5.09457635e-02, -6.05094576e+00, -3.05094576e+00],
       [-6.12910891e+00, -2.12910891e+00, -1.29108909e-01]])

In [218]:
from scipy import special

In [219]:
special.log_softmax(x_in, axis=1)

array([[-3.15072161e-01, -6.31507216e+00, -1.31507216e+00],
       [-4.01904501e+00, -7.01904501e+00, -1.90450079e-02],
       [-3.38489890e-03, -7.00338490e+00, -6.00338490e+00],
       [-5.09457635e-02, -6.05094576e+00, -3.05094576e+00],
       [-6.12910891e+00, -2.12910891e+00, -1.29108909e-01]])

In [220]:
def smax(x_in):
    
    x_out = np.subtract(x_in, x_in.max(axis=1, keepdims=True))
    
    x_out = np.exp(x_out)/np.sum(np.exp(x_out), axis=1, keepdims=True)
    
    return x_out

In [221]:
smax(x_in)

array([[7.29736214e-01, 1.80883523e-03, 2.68454951e-01],
       [1.79701181e-02, 8.94679497e-04, 9.81135202e-01],
       [9.96620823e-01, 9.08800555e-04, 2.47037604e-03],
       [9.50330212e-01, 2.35563308e-03, 4.73141552e-02],
       [2.17852136e-03, 1.18943236e-01, 8.78878243e-01]])

In [222]:
special.softmax(x_in, axis=1)

array([[7.29736214e-01, 1.80883523e-03, 2.68454951e-01],
       [1.79701181e-02, 8.94679497e-04, 9.81135202e-01],
       [9.96620823e-01, 9.08800555e-04, 2.47037604e-03],
       [9.50330212e-01, 2.35563308e-03, 4.73141552e-02],
       [2.17852136e-03, 1.18943236e-01, 8.78878243e-01]])

In [223]:
x_in

array([[6, 0, 5],
       [5, 2, 9],
       [8, 1, 2],
       [8, 2, 5],
       [3, 7, 9]])

In [224]:
s = smax(x_in)
s

array([[7.29736214e-01, 1.80883523e-03, 2.68454951e-01],
       [1.79701181e-02, 8.94679497e-04, 9.81135202e-01],
       [9.96620823e-01, 9.08800555e-04, 2.47037604e-03],
       [9.50330212e-01, 2.35563308e-03, 4.73141552e-02],
       [2.17852136e-03, 1.18943236e-01, 8.78878243e-01]])

In [225]:
w = s[0].copy()
w

array([0.72973621, 0.00180884, 0.26845495])

In [226]:
I = np.eye(3)

In [227]:
I 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [228]:
I - w

array([[ 0.27026379, -0.00180884, -0.26845495],
       [-0.72973621,  0.99819116, -0.26845495],
       [-0.72973621, -0.00180884,  0.73154505]])

In [229]:
w[:, None]

array([[0.72973621],
       [0.00180884],
       [0.26845495]])

In [230]:
w[:, None] * (I - w)

array([[ 0.19722127, -0.00131997, -0.1959013 ],
       [-0.00131997,  0.00180556, -0.00048559],
       [-0.1959013 , -0.00048559,  0.19638689]])

# Example derivative of Softmax:

In [231]:
x_in

array([[6, 0, 5],
       [5, 2, 9],
       [8, 1, 2],
       [8, 2, 5],
       [3, 7, 9]])

In [232]:
x_in[:, None, :]

array([[[6, 0, 5]],

       [[5, 2, 9]],

       [[8, 1, 2]],

       [[8, 2, 5]],

       [[3, 7, 9]]])

In [233]:
s = smax(x_in)
s

array([[7.29736214e-01, 1.80883523e-03, 2.68454951e-01],
       [1.79701181e-02, 8.94679497e-04, 9.81135202e-01],
       [9.96620823e-01, 9.08800555e-04, 2.47037604e-03],
       [9.50330212e-01, 2.35563308e-03, 4.73141552e-02],
       [2.17852136e-03, 1.18943236e-01, 8.78878243e-01]])

In [234]:
s[:, None, :]

array([[[7.29736214e-01, 1.80883523e-03, 2.68454951e-01]],

       [[1.79701181e-02, 8.94679497e-04, 9.81135202e-01]],

       [[9.96620823e-01, 9.08800555e-04, 2.47037604e-03]],

       [[9.50330212e-01, 2.35563308e-03, 4.73141552e-02]],

       [[2.17852136e-03, 1.18943236e-01, 8.78878243e-01]]])

In [235]:
np.eye(3) - s[:, None, :]

array([[[ 2.70263786e-01, -1.80883523e-03, -2.68454951e-01],
        [-7.29736214e-01,  9.98191165e-01, -2.68454951e-01],
        [-7.29736214e-01, -1.80883523e-03,  7.31545049e-01]],

       [[ 9.82029882e-01, -8.94679497e-04, -9.81135202e-01],
        [-1.79701181e-02,  9.99105321e-01, -9.81135202e-01],
        [-1.79701181e-02, -8.94679497e-04,  1.88647976e-02]],

       [[ 3.37917659e-03, -9.08800555e-04, -2.47037604e-03],
        [-9.96620823e-01,  9.99091199e-01, -2.47037604e-03],
        [-9.96620823e-01, -9.08800555e-04,  9.97529624e-01]],

       [[ 4.96697883e-02, -2.35563308e-03, -4.73141552e-02],
        [-9.50330212e-01,  9.97644367e-01, -4.73141552e-02],
        [-9.50330212e-01, -2.35563308e-03,  9.52685845e-01]],

       [[ 9.97821479e-01, -1.18943236e-01, -8.78878243e-01],
        [-2.17852136e-03,  8.81056764e-01, -8.78878243e-01],
        [-2.17852136e-03, -1.18943236e-01,  1.21121757e-01]]])

In [236]:
s[:, :, None]

array([[[7.29736214e-01],
        [1.80883523e-03],
        [2.68454951e-01]],

       [[1.79701181e-02],
        [8.94679497e-04],
        [9.81135202e-01]],

       [[9.96620823e-01],
        [9.08800555e-04],
        [2.47037604e-03]],

       [[9.50330212e-01],
        [2.35563308e-03],
        [4.73141552e-02]],

       [[2.17852136e-03],
        [1.18943236e-01],
        [8.78878243e-01]]])

In [237]:
dsdxT.shape

(5, 3, 3)

In [238]:
dLdsT.shape

(5, 1, 3)

In [239]:
dsdxT.shape

(5, 3, 3)

In [240]:
np.array([ 2.38438706e-02, -1.74312661e-02, -6.41260445e-03]) * np.array([7, 2, 7])

array([ 0.16690709, -0.03486253, -0.04488823])

In [241]:
sum([ 1.66907094e-01,-1.22018863e-01, -4.48882311e-02])

-1.000000013351432e-10

In [242]:
dsdxT = s[:, :, None] * (np.eye(3) - s[:, None, :]) #dxT = dx
dsdxT

array([[[ 1.97221272e-01, -1.31997257e-03, -1.95901299e-01],
        [-1.31997257e-03,  1.80556334e-03, -4.85590772e-04],
        [-1.95901299e-01, -4.85590772e-04,  1.96386890e-01]],

       [[ 1.76471929e-02, -1.60774962e-05, -1.76311154e-02],
        [-1.60774962e-05,  8.93879045e-04, -8.77801549e-04],
        [-1.76311154e-02, -8.77801549e-04,  1.85089170e-02]],

       [[ 3.36775776e-03, -9.05729558e-04, -2.46202820e-03],
        [-9.05729558e-04,  9.07974637e-04, -2.24507911e-06],
        [-2.46202820e-03, -2.24507911e-06,  2.46427328e-03]],

       [[ 4.72027004e-02, -2.23862928e-03, -4.49640711e-02],
        [-2.23862928e-03,  2.35008407e-03, -1.11454789e-04],
        [-4.49640711e-02, -1.11454789e-04,  4.50755259e-02]],

       [[ 2.17377540e-03, -2.59120380e-04, -1.91465502e-03],
        [-2.59120380e-04,  1.04795743e-01, -1.04536622e-01],
        [-1.91465502e-03, -1.04536622e-01,  1.06451277e-01]]])

In [243]:
dLdsT = np.random.randint(0, 10, (5, 1, 3))
dLdsT

array([[[9, 9, 9]],

       [[0, 3, 2]],

       [[4, 2, 1]],

       [[1, 6, 6]],

       [[9, 6, 1]]])

In [244]:
np.multiply(dLdsT, dsdxT)

array([[[ 1.77499145e+00, -1.18797531e-02, -1.76311169e+00],
        [-1.18797531e-02,  1.62500701e-02, -4.37031695e-03],
        [-1.76311169e+00, -4.37031695e-03,  1.76748201e+00]],

       [[ 0.00000000e+00, -4.82324886e-05, -3.52622309e-02],
        [-0.00000000e+00,  2.68163714e-03, -1.75560310e-03],
        [-0.00000000e+00, -2.63340465e-03,  3.70178340e-02]],

       [[ 1.34710310e-02, -1.81145912e-03, -2.46202820e-03],
        [-3.62291823e-03,  1.81594927e-03, -2.24507911e-06],
        [-9.84811279e-03, -4.49015823e-06,  2.46427328e-03]],

       [[ 4.72027004e-02, -1.34317757e-02, -2.69784427e-01],
        [-2.23862928e-03,  1.41005044e-02, -6.68728735e-04],
        [-4.49640711e-02, -6.68728735e-04,  2.70453156e-01]],

       [[ 1.95639786e-02, -1.55472228e-03, -1.91465502e-03],
        [-2.33208342e-03,  6.28774455e-01, -1.04536622e-01],
        [-1.72318952e-02, -6.27219733e-01,  1.06451277e-01]]])

In [254]:
sum([-4.49640711e-02, -6.68728735e-04,  2.70453156e-01])

0.22482035616499996

In [247]:
np.multiply(dLdsT, dsdxT).sum(axis=2)

array([[ 0.00000000e+00, -1.73472348e-18,  2.22044605e-16],
       [-3.53104633e-02,  9.26034038e-04,  3.43844293e-02],
       [ 9.19754371e-03, -1.80921404e-03, -7.38832967e-03],
       [-2.36013502e-01,  1.11931464e-02,  2.24820356e-01],
       [ 1.60946013e-02,  5.21905750e-01, -5.38000351e-01]])

In [248]:
np.multiply(dLdsT, dsdxT).sum(axis=2).shape

(5, 3)

In [249]:
np.multiply(dLdsT, dsdxT).shape

(5, 3, 3)

In [251]:
dLdxT = np.matmul(dLdsT, dsdxT)
np.squeeze(dLdxT)

array([[ 0.00000000e+00, -1.73472348e-18,  2.22044605e-16],
       [-3.53104633e-02,  9.26034038e-04,  3.43844293e-02],
       [ 9.19754371e-03, -1.80921404e-03, -7.38832967e-03],
       [-2.36013502e-01,  1.11931464e-02,  2.24820356e-01],
       [ 1.60946013e-02,  5.21905750e-01, -5.38000351e-01]])

In [147]:
sum([ 2.38438706e-02, -3.48625323e-02, -2.56504178e-02])

-0.03666907949999999

In [148]:
sum([-1.74312661e-02,  3.50974342e-02, -4.69803790e-04])

0.01719636431

In [164]:
dsdxT

array([[[ 2.38438706e-02, -1.74312661e-02, -6.41260445e-03],
        [-1.74312661e-02,  1.75487171e-02, -1.17450947e-04],
        [-6.41260445e-03, -1.17450947e-04,  6.53005540e-03]],

       [[ 2.95299969e-04, -2.60099350e-04, -3.52006192e-05],
        [-2.60099350e-04,  1.05191666e-01, -1.04931567e-01],
        [-3.52006192e-05, -1.04931567e-01,  1.04966768e-01]],

       [[ 1.08924193e-01, -1.03758368e-01, -5.16582496e-03],
        [-1.03758368e-01,  1.04457486e-01, -6.99118384e-04],
        [-5.16582496e-03, -6.99118384e-04,  5.86494335e-03]],

       [[ 2.00982401e-01, -1.91450635e-01, -9.53176587e-03],
        [-1.91450635e-01,  1.94957176e-01, -3.50654070e-03],
        [-9.53176587e-03, -3.50654070e-03,  1.30383066e-02]],

       [[ 4.50755259e-02, -1.11454789e-04, -4.49640711e-02],
        [-1.11454789e-04,  2.35008407e-03, -2.23862928e-03],
        [-4.49640711e-02, -2.23862928e-03,  4.72027004e-02]]])

In [165]:
dLdsT

array([[[7, 2, 7]],

       [[5, 7, 8]],

       [[1, 0, 8]],

       [[3, 3, 5]],

       [[7, 6, 1]]])

In [252]:
np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))).sum(axis=2)

NameError: name 'batch_size' is not defined

### From notebook

In [151]:
s

array([[0.03511903, 0.25949646, 0.70538451],
       [0.84379473, 0.04201007, 0.1141952 ],
       [0.94649912, 0.04712342, 0.00637746],
       [0.10650698, 0.78698604, 0.10650698],
       [0.49832117, 0.49832117, 0.00335766]])

In [ ]:
batch_size, n_feats = self.output.shape
a = self.output.reshape(batch_size, n_feats, -1)
b = self.output.reshape(batch_size, -1, n_feats)
self.gradInput = np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))).sum(axis=2)

In [152]:
batch_size, n_feats = s.shape

In [153]:
batch_size

5

In [154]:
n_feats

3

In [155]:
a = s.reshape(batch_size, n_feats, -1)

In [156]:
a

array([[[0.03511903],
        [0.25949646],
        [0.70538451]],

       [[0.84379473],
        [0.04201007],
        [0.1141952 ]],

       [[0.94649912],
        [0.04712342],
        [0.00637746]],

       [[0.10650698],
        [0.78698604],
        [0.10650698]],

       [[0.49832117],
        [0.49832117],
        [0.00335766]]])

In [159]:
b = s.reshape(batch_size, -1, n_feats)
b

array([[[0.03511903, 0.25949646, 0.70538451]],

       [[0.84379473, 0.04201007, 0.1141952 ]],

       [[0.94649912, 0.04712342, 0.00637746]],

       [[0.10650698, 0.78698604, 0.10650698]],

       [[0.49832117, 0.49832117, 0.00335766]]])

In [160]:
dLdsT

array([[[7, 5, 6]],

       [[8, 2, 0]],

       [[2, 0, 6]],

       [[3, 8, 6]],

       [[6, 7, 3]]])

In [162]:
gradOutput = np.random.random((n_batch, n_feats))
gradOutput.reshape(batch_size, -1, n_feats)

array([[[0.01930357, 0.49218674, 0.45277248]],

       [[0.38457102, 0.50025952, 0.82578179]],

       [[0.14627171, 0.98986419, 0.7306874 ]],

       [[0.11548067, 0.16712459, 0.66597947]],

       [[0.43219543, 0.38642148, 0.61332477]]])

In [163]:
a

array([[[0.03511903],
        [0.25949646],
        [0.70538451]],

       [[0.84379473],
        [0.04201007],
        [0.1141952 ]],

       [[0.94649912],
        [0.04712342],
        [0.00637746]],

       [[0.10650698],
        [0.78698604],
        [0.10650698]],

       [[0.49832117],
        [0.49832117],
        [0.00335766]]])

In [164]:
s[:,:, None]

array([[[0.03511903],
        [0.25949646],
        [0.70538451]],

       [[0.84379473],
        [0.04201007],
        [0.1141952 ]],

       [[0.94649912],
        [0.04712342],
        [0.00637746]],

       [[0.10650698],
        [0.78698604],
        [0.10650698]],

       [[0.49832117],
        [0.49832117],
        [0.00335766]]])

In [165]:
np.multiply(np.eye(n_feats), a)

array([[[0.03511903, 0.        , 0.        ],
        [0.        , 0.25949646, 0.        ],
        [0.        , 0.        , 0.70538451]],

       [[0.84379473, 0.        , 0.        ],
        [0.        , 0.04201007, 0.        ],
        [0.        , 0.        , 0.1141952 ]],

       [[0.94649912, 0.        , 0.        ],
        [0.        , 0.04712342, 0.        ],
        [0.        , 0.        , 0.00637746]],

       [[0.10650698, 0.        , 0.        ],
        [0.        , 0.78698604, 0.        ],
        [0.        , 0.        , 0.10650698]],

       [[0.49832117, 0.        , 0.        ],
        [0.        , 0.49832117, 0.        ],
        [0.        , 0.        , 0.00335766]]])

In [166]:
np.multiply(a, b)

array([[[1.23334605e-03, 9.11326319e-03, 2.47724177e-02],
        [9.11326319e-03, 6.73384129e-02, 1.83044784e-01],
        [2.47724177e-02, 1.83044784e-01, 4.97567311e-01]],

       [[7.11989554e-01, 3.54478726e-02, 9.63573079e-02],
        [3.54478726e-02, 1.76484566e-03, 4.79734788e-03],
        [9.63573079e-02, 4.79734788e-03, 1.30405436e-02]],

       [[8.95860589e-01, 4.46022724e-02, 6.03626117e-03],
        [4.46022724e-02, 2.22061638e-03, 3.00527747e-04],
        [6.03626117e-03, 3.00527747e-04, 4.06720078e-05]],

       [[1.13437366e-02, 8.38195058e-02, 1.13437366e-02],
        [8.38195058e-02, 6.19347031e-01, 8.38195058e-02],
        [1.13437366e-02, 8.38195058e-02, 1.13437366e-02]],

       [[2.48323988e-01, 2.48323988e-01, 1.67319387e-03],
        [2.48323988e-01, 2.48323988e-01, 1.67319387e-03],
        [1.67319387e-03, 1.67319387e-03, 1.12738916e-05]]])

In [167]:
np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))

array([[[ 0.03388568, -0.00911326, -0.02477242],
        [-0.00911326,  0.19215805, -0.18304478],
        [-0.02477242, -0.18304478,  0.2078172 ]],

       [[ 0.13180518, -0.03544787, -0.09635731],
        [-0.03544787,  0.04024522, -0.00479735],
        [-0.09635731, -0.00479735,  0.10115466]],

       [[ 0.05063853, -0.04460227, -0.00603626],
        [-0.04460227,  0.0449028 , -0.00030053],
        [-0.00603626, -0.00030053,  0.00633679]],

       [[ 0.09516324, -0.08381951, -0.01134374],
        [-0.08381951,  0.16763901, -0.08381951],
        [-0.01134374, -0.08381951,  0.09516324]],

       [[ 0.24999718, -0.24832399, -0.00167319],
        [-0.24832399,  0.24999718, -0.00167319],
        [-0.00167319, -0.00167319,  0.00334639]]])

In [168]:
dsdxT

array([[[ 0.03388568, -0.00911326, -0.02477242],
        [-0.00911326,  0.19215805, -0.18304478],
        [-0.02477242, -0.18304478,  0.2078172 ]],

       [[ 0.13180518, -0.03544787, -0.09635731],
        [-0.03544787,  0.04024522, -0.00479735],
        [-0.09635731, -0.00479735,  0.10115466]],

       [[ 0.05063853, -0.04460227, -0.00603626],
        [-0.04460227,  0.0449028 , -0.00030053],
        [-0.00603626, -0.00030053,  0.00633679]],

       [[ 0.09516324, -0.08381951, -0.01134374],
        [-0.08381951,  0.16763901, -0.08381951],
        [-0.01134374, -0.08381951,  0.09516324]],

       [[ 0.24999718, -0.24832399, -0.00167319],
        [-0.24832399,  0.24999718, -0.00167319],
        [-0.00167319, -0.00167319,  0.00334639]]])

In [170]:
gradOutput.reshape(batch_size, -1, n_feats).shape

(5, 1, 3)

In [183]:
np.random.randint(0, 10, (5, 1, 3)).shape

(5, 1, 3)

In [186]:
gradOutput.reshape(batch_size, -1, n_feats)

array([[[0.01930357, 0.49218674, 0.45277248]],

       [[0.38457102, 0.50025952, 0.82578179]],

       [[0.14627171, 0.98986419, 0.7306874 ]],

       [[0.11548067, 0.16712459, 0.66597947]],

       [[0.43219543, 0.38642148, 0.61332477]]])

In [187]:
np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))

array([[[ 0.03388568, -0.00911326, -0.02477242],
        [-0.00911326,  0.19215805, -0.18304478],
        [-0.02477242, -0.18304478,  0.2078172 ]],

       [[ 0.13180518, -0.03544787, -0.09635731],
        [-0.03544787,  0.04024522, -0.00479735],
        [-0.09635731, -0.00479735,  0.10115466]],

       [[ 0.05063853, -0.04460227, -0.00603626],
        [-0.04460227,  0.0449028 , -0.00030053],
        [-0.00603626, -0.00030053,  0.00633679]],

       [[ 0.09516324, -0.08381951, -0.01134374],
        [-0.08381951,  0.16763901, -0.08381951],
        [-0.01134374, -0.08381951,  0.09516324]],

       [[ 0.24999718, -0.24832399, -0.00167319],
        [-0.24832399,  0.24999718, -0.00167319],
        [-0.00167319, -0.00167319,  0.00334639]]])

In [185]:
np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b)))

array([[[ 0.00065411, -0.00448543, -0.01121627],
        [-0.00017592,  0.09457764, -0.08287764],
        [-0.0004782 , -0.09009221,  0.09409391]],

       [[ 0.05068845, -0.01773314, -0.07957011],
        [-0.01363222,  0.02013305, -0.00396156],
        [-0.03705623, -0.00239992,  0.08353167]],

       [[ 0.00740698, -0.04415019, -0.00441062],
        [-0.00652405,  0.04444767, -0.00021959],
        [-0.00088293, -0.00029748,  0.00463021]],

       [[ 0.01098952, -0.0140083 , -0.0075547 ],
        [-0.00967953,  0.0280166 , -0.05582207],
        [-0.00130998, -0.0140083 ,  0.06337677]],

       [[ 0.10804764, -0.09595772, -0.00102621],
        [-0.10732449,  0.09660428, -0.00102621],
        [-0.00072315, -0.00064656,  0.00205242]]])

In [184]:
np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))).sum(axis=2)

array([[-0.01504758,  0.01152408,  0.0035235 ],
       [-0.04661479,  0.00253927,  0.04407553],
       [-0.04115383,  0.03770403,  0.0034498 ],
       [-0.01057348, -0.037485  ,  0.04805848],
       [ 0.01106371, -0.01174642,  0.00068272]])

In [188]:
dLdsT

array([[[7, 5, 6]],

       [[8, 2, 0]],

       [[2, 0, 6]],

       [[3, 8, 6]],

       [[6, 7, 3]]])

In [175]:
dLdxT.shape

(5, 1, 3)

In [173]:
dLdxT.sum(axis=2)

array([[ 6.10622664e-16],
       [-9.99200722e-16],
       [-2.84494650e-16],
       [ 1.11022302e-15],
       [ 6.86950496e-16]])

In [176]:
dLdxT.sum(axis=2).shape

(5, 1)

In [182]:
sum([ 0.9835457 , -0.20309254, -0.78045316])

0.0

In [180]:
print("{:e}".format(0.04299894 + -0.20127131 + 0.15827237))

0.000000e+00


---

# Example derivative of LogSoftMax

In [140]:
x_in

array([[2, 4, 5],
       [3, 0, 1],
       [6, 3, 1],
       [1, 3, 1],
       [9, 9, 4]])

In [142]:
s = smax(x_in)
s

array([[0.03511903, 0.25949646, 0.70538451],
       [0.84379473, 0.04201007, 0.1141952 ],
       [0.94649912, 0.04712342, 0.00637746],
       [0.10650698, 0.78698604, 0.10650698],
       [0.49832117, 0.49832117, 0.00335766]])

In [146]:
s[:,:, None]

array([[[0.03511903],
        [0.25949646],
        [0.70538451]],

       [[0.84379473],
        [0.04201007],
        [0.1141952 ]],

       [[0.94649912],
        [0.04712342],
        [0.00637746]],

       [[0.10650698],
        [0.78698604],
        [0.10650698]],

       [[0.49832117],
        [0.49832117],
        [0.00335766]]])

In [149]:
res2 = np.ones(3) * s[:,:, None]
res2

array([[[0.03511903, 0.03511903, 0.03511903],
        [0.25949646, 0.25949646, 0.25949646],
        [0.70538451, 0.70538451, 0.70538451]],

       [[0.84379473, 0.84379473, 0.84379473],
        [0.04201007, 0.04201007, 0.04201007],
        [0.1141952 , 0.1141952 , 0.1141952 ]],

       [[0.94649912, 0.94649912, 0.94649912],
        [0.04712342, 0.04712342, 0.04712342],
        [0.00637746, 0.00637746, 0.00637746]],

       [[0.10650698, 0.10650698, 0.10650698],
        [0.78698604, 0.78698604, 0.78698604],
        [0.10650698, 0.10650698, 0.10650698]],

       [[0.49832117, 0.49832117, 0.49832117],
        [0.49832117, 0.49832117, 0.49832117],
        [0.00335766, 0.00335766, 0.00335766]]])

In [150]:
res3 = np.eye(3) - res2
res3

array([[[ 0.96488097, -0.03511903, -0.03511903],
        [-0.25949646,  0.74050354, -0.25949646],
        [-0.70538451, -0.70538451,  0.29461549]],

       [[ 0.15620527, -0.84379473, -0.84379473],
        [-0.04201007,  0.95798993, -0.04201007],
        [-0.1141952 , -0.1141952 ,  0.8858048 ]],

       [[ 0.05350088, -0.94649912, -0.94649912],
        [-0.04712342,  0.95287658, -0.04712342],
        [-0.00637746, -0.00637746,  0.99362254]],

       [[ 0.89349302, -0.10650698, -0.10650698],
        [-0.78698604,  0.21301396, -0.78698604],
        [-0.10650698, -0.10650698,  0.89349302]],

       [[ 0.50167883, -0.49832117, -0.49832117],
        [-0.49832117,  0.50167883, -0.49832117],
        [-0.00335766, -0.00335766,  0.99664234]]])

In [86]:
gradOutput = np.random.randint(0, 10, (5, 3, 1))

In [87]:
gradOutput

array([[[8],
        [1],
        [7]],

       [[7],
        [9],
        [6]],

       [[2],
        [0],
        [9]],

       [[4],
        [5],
        [9]],

       [[4],
        [7],
        [5]]])

In [88]:
res3.shape

(5, 3, 3)

In [89]:
gradOutput.shape

(5, 3, 1)

In [90]:
np.matmul(res3, gradOutput)

array([[[ 2.52185974],
        [-4.47814026],
        [ 1.52185974]],

       [[ 0.03017507],
        [ 2.03017507],
        [-0.96982493]],

       [[ 0.04960461],
        [-1.95039539],
        [ 7.04960461]],

       [[-1.31952094],
        [-0.31952094],
        [ 3.68047906]],

       [[-1.49832117],
        [ 1.50167883],
        [-0.49832117]]])

In [91]:
np.sum(np.matmul(res3, gradOutput), axis=0)

array([[-0.2162027],
       [-3.2162027],
       [10.7837973]])