In [220]:
import numpy as np

In [221]:
np.random.randn(5, 10).shape

(5, 10)

In [222]:
stdv = 0.05

In [223]:
np.random.uniform(-stdv, stdv, size = 4)

array([0.0425921 , 0.01022589, 0.00095821, 0.00696684])

In [224]:
b = np.random.uniform(-stdv, stdv, size = (1,4))
b

array([[-0.0202104 , -0.0453231 ,  0.0032572 ,  0.02342756]])

In [225]:
n_in = 3
n_out = 4

In [226]:
W = np.random.random((n_in, n_out))

In [227]:
W

array([[0.4348814 , 0.96196761, 0.08448866, 0.37663733],
       [0.74136718, 0.84724226, 0.85870648, 0.83283132],
       [0.80586997, 0.55067863, 0.99338934, 0.21780009]])

In [228]:
gradOutput = np.random.random((1, n_out))

In [229]:
gradOutput.dot(W.T)

array([[1.0080258 , 1.45741004, 1.36641069]])

In [230]:
x_in = np.random.random((2, n_in))
x_in

array([[0.53066636, 0.06407891, 0.39434727],
       [0.17308195, 0.85759676, 0.56762643]])

In [231]:
x_in[:, None, :]

array([[[0.53066636, 0.06407891, 0.39434727]],

       [[0.17308195, 0.85759676, 0.56762643]]])

In [232]:
gradOutput

array([[0.92299535, 0.59691912, 0.29129867, 0.02072019]])

In [233]:
gradOutput[:,:, None]

array([[[0.92299535],
        [0.59691912],
        [0.29129867],
        [0.02072019]]])

In [234]:
x_in[:, None, :] * gradOutput[:,:, None]

array([[[0.48980258, 0.05914454, 0.3639807 ],
        [0.3167649 , 0.03824993, 0.23539343],
        [0.15458241, 0.0186661 , 0.11487284],
        [0.01099551, 0.00132773, 0.00817095]],

       [[0.15975384, 0.79155782, 0.52391656],
        [0.10331593, 0.5119159 , 0.33882707],
        [0.05041854, 0.2498168 , 0.16534883],
        [0.00358629, 0.01776956, 0.01176133]]])

In [235]:
n_batch = 5

In [236]:
x_in = np.random.randint(0, 10, size=(n_batch, n_in))
x_in[:, None, :]

array([[[9, 7, 0]],

       [[8, 1, 3]],

       [[2, 3, 5]],

       [[5, 8, 7]],

       [[4, 3, 4]]])

In [237]:
x_in

array([[9, 7, 0],
       [8, 1, 3],
       [2, 3, 5],
       [5, 8, 7],
       [4, 3, 4]])

In [238]:
dx_out = np.random.randint(0, 10, size=(n_batch, n_out))
dx_out[:, :, None]

array([[[9],
        [2],
        [4],
        [7]],

       [[4],
        [7],
        [5],
        [7]],

       [[9],
        [3],
        [0],
        [4]],

       [[4],
        [3],
        [5],
        [0]],

       [[2],
        [4],
        [1],
        [0]]])

In [239]:
dx_out

array([[9, 2, 4, 7],
       [4, 7, 5, 7],
       [9, 3, 0, 4],
       [4, 3, 5, 0],
       [2, 4, 1, 0]])

for `n_batch` $> 1$, `np.outer` doesn't work as expected

In [240]:
np.outer(x_in, dx_out).T

array([[81, 63,  0, 72,  9, 27, 18, 27, 45, 45, 72, 63, 36, 27, 36],
       [18, 14,  0, 16,  2,  6,  4,  6, 10, 10, 16, 14,  8,  6,  8],
       [36, 28,  0, 32,  4, 12,  8, 12, 20, 20, 32, 28, 16, 12, 16],
       [63, 49,  0, 56,  7, 21, 14, 21, 35, 35, 56, 49, 28, 21, 28],
       [36, 28,  0, 32,  4, 12,  8, 12, 20, 20, 32, 28, 16, 12, 16],
       [63, 49,  0, 56,  7, 21, 14, 21, 35, 35, 56, 49, 28, 21, 28],
       [45, 35,  0, 40,  5, 15, 10, 15, 25, 25, 40, 35, 20, 15, 20],
       [63, 49,  0, 56,  7, 21, 14, 21, 35, 35, 56, 49, 28, 21, 28],
       [81, 63,  0, 72,  9, 27, 18, 27, 45, 45, 72, 63, 36, 27, 36],
       [27, 21,  0, 24,  3,  9,  6,  9, 15, 15, 24, 21, 12,  9, 12],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [36, 28,  0, 32,  4, 12,  8, 12, 20, 20, 32, 28, 16, 12, 16],
       [36, 28,  0, 32,  4, 12,  8, 12, 20, 20, 32, 28, 16, 12, 16],
       [27, 21,  0, 24,  3,  9,  6,  9, 15, 15, 24, 21, 12,  9, 12],
       [45, 35,  0, 40,  5, 15, 10

In [241]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[81, 63,  0],
        [18, 14,  0],
        [36, 28,  0],
        [63, 49,  0]],

       [[32,  4, 12],
        [56,  7, 21],
        [40,  5, 15],
        [56,  7, 21]],

       [[18, 27, 45],
        [ 6,  9, 15],
        [ 0,  0,  0],
        [ 8, 12, 20]],

       [[20, 32, 28],
        [15, 24, 21],
        [25, 40, 35],
        [ 0,  0,  0]],

       [[ 8,  6,  8],
        [16, 12, 16],
        [ 4,  3,  4],
        [ 0,  0,  0]]])

In [242]:
result = x_in[:, None, :] * dx_out[:, :, None]
result

array([[[81, 63,  0],
        [18, 14,  0],
        [36, 28,  0],
        [63, 49,  0]],

       [[32,  4, 12],
        [56,  7, 21],
        [40,  5, 15],
        [56,  7, 21]],

       [[18, 27, 45],
        [ 6,  9, 15],
        [ 0,  0,  0],
        [ 8, 12, 20]],

       [[20, 32, 28],
        [15, 24, 21],
        [25, 40, 35],
        [ 0,  0,  0]],

       [[ 8,  6,  8],
        [16, 12, 16],
        [ 4,  3,  4],
        [ 0,  0,  0]]])

In [243]:
np.sum(result, axis=0)

array([[159, 132,  93],
       [111,  66,  73],
       [105,  76,  54],
       [127,  68,  41]])

In [244]:
dx_out

array([[9, 2, 4, 7],
       [4, 7, 5, 7],
       [9, 3, 0, 4],
       [4, 3, 5, 0],
       [2, 4, 1, 0]])

In [245]:
np.sum(dx_out, axis=0)

array([28, 19, 15, 18])

In [246]:
s = x_in[:, None, :]

In [247]:
s

array([[[9, 7, 0]],

       [[8, 1, 3]],

       [[2, 3, 5]],

       [[5, 8, 7]],

       [[4, 3, 4]]])

In [248]:
s.shape

(5, 1, 3)

In [249]:
x_in

array([[9, 7, 0],
       [8, 1, 3],
       [2, 3, 5],
       [5, 8, 7],
       [4, 3, 4]])

In [250]:
x_in.shape

(5, 3)

In [251]:
s.ndim

3

### =========

In [252]:
d = dx_out[:, :, None]
d

array([[[9],
        [2],
        [4],
        [7]],

       [[4],
        [7],
        [5],
        [7]],

       [[9],
        [3],
        [0],
        [4]],

       [[4],
        [3],
        [5],
        [0]],

       [[2],
        [4],
        [1],
        [0]]])

In [253]:
d.shape

(5, 4, 1)

In [254]:
dx_out

array([[9, 2, 4, 7],
       [4, 7, 5, 7],
       [9, 3, 0, 4],
       [4, 3, 5, 0],
       [2, 4, 1, 0]])

In [255]:
dx_out.shape

(5, 4)

In [256]:
np.arange(3, 10)[:, None]

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

A way to understand numpy array:

When dealing with $0$, $1$ or $2$ dimensional array, some of us try to give an interpretation through scalars, vectors and matrices. This is fine, since the definitions coincide but how od we picture and array of $(n, m, p)$ dimensions? 

- If `s` is a `(n, m)`-matrix and `d` is a `(n, q)`-matrix, then what does `s[:, None, :]` or `d[:,:, None]` mean? 
- Why does `s[:, None, :] * d[:,:, None]` work and what does it give?

One way of understanding this is, instead of looking at a $n$-dimensional array as an _array of elements_ we can look at it as an _array of arrays_.

- shape `(5, 4)`:
    - There are `5` rows. Each of those rows is an array of shape `(4,)`. That is and array of `4` elements.
    
    
- shape `(5, 1, 3)`:
    - There are `5` rows. Let's look at one of them. That row consists of a `(1, 3)` array. That is, in this row there is just `1` array of 3 elements.
    
    
- shape `(5, 4, 1)`: 
    - There are `5` rows. Let's look at one of them. That row consists of a `(4, 1)` array. That is, in this row there are `4` different arrays, each containing 1 element.

In [257]:
x_in[:, None, :]

array([[[9, 7, 0]],

       [[8, 1, 3]],

       [[2, 3, 5]],

       [[5, 8, 7]],

       [[4, 3, 4]]])

In [258]:
dx_out[:, :, None]

array([[[9],
        [2],
        [4],
        [7]],

       [[4],
        [7],
        [5],
        [7]],

       [[9],
        [3],
        [0],
        [4]],

       [[4],
        [3],
        [5],
        [0]],

       [[2],
        [4],
        [1],
        [0]]])

In [259]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[81, 63,  0],
        [18, 14,  0],
        [36, 28,  0],
        [63, 49,  0]],

       [[32,  4, 12],
        [56,  7, 21],
        [40,  5, 15],
        [56,  7, 21]],

       [[18, 27, 45],
        [ 6,  9, 15],
        [ 0,  0,  0],
        [ 8, 12, 20]],

       [[20, 32, 28],
        [15, 24, 21],
        [25, 40, 35],
        [ 0,  0,  0]],

       [[ 8,  6,  8],
        [16, 12, 16],
        [ 4,  3,  4],
        [ 0,  0,  0]]])

In [260]:
dx_out[:, :, None] * x_in[:, None, :]

array([[[81, 63,  0],
        [18, 14,  0],
        [36, 28,  0],
        [63, 49,  0]],

       [[32,  4, 12],
        [56,  7, 21],
        [40,  5, 15],
        [56,  7, 21]],

       [[18, 27, 45],
        [ 6,  9, 15],
        [ 0,  0,  0],
        [ 8, 12, 20]],

       [[20, 32, 28],
        [15, 24, 21],
        [25, 40, 35],
        [ 0,  0,  0]],

       [[ 8,  6,  8],
        [16, 12, 16],
        [ 4,  3,  4],
        [ 0,  0,  0]]])

In [261]:
(dx_out[:, :, None] * x_in[:, None, :]).shape == (dx_out[:, :, None] * x_in[:, None, :]).shape

True

In [262]:
(dx_out[:, :, None] * x_in[:, None, :]).shape

(5, 4, 3)

In [263]:
(dx_out[:, :, None] * x_in[:, None, :]).shape

(5, 4, 3)

In [264]:
def log_smax(x_in):
    
    x_out = np.subtract(x_in, x_in.max(axis=1, keepdims=True))
    
    x_out = x_out - np.log(np.sum(np.exp(x_out), axis=1, keepdims=True))
    
    return x_out

In [265]:
x_in

array([[9, 7, 0],
       [8, 1, 3],
       [2, 3, 5],
       [5, 8, 7],
       [4, 3, 4]])

In [266]:
log_smax(x_in)

array([[-1.27036704e-01, -2.12703670e+00, -9.12703670e+00],
       [-7.62071739e-03, -7.00762072e+00, -5.00762072e+00],
       [-3.16984602e+00, -2.16984602e+00, -1.69846020e-01],
       [-3.34901222e+00, -3.49012217e-01, -1.34901222e+00],
       [-8.61994804e-01, -1.86199480e+00, -8.61994804e-01]])

In [267]:
from scipy import special

In [268]:
special.log_softmax(x_in, axis=1)

array([[-1.27036704e-01, -2.12703670e+00, -9.12703670e+00],
       [-7.62071739e-03, -7.00762072e+00, -5.00762072e+00],
       [-3.16984602e+00, -2.16984602e+00, -1.69846020e-01],
       [-3.34901222e+00, -3.49012217e-01, -1.34901222e+00],
       [-8.61994804e-01, -1.86199480e+00, -8.61994804e-01]])

In [269]:
def smax(x_in):
    
    x_out = np.subtract(x_in, x_in.max(axis=1, keepdims=True))
    
    x_out = np.exp(x_out)/np.sum(np.exp(x_out), axis=1, keepdims=True)
    
    return x_out

In [270]:
smax(x_in)

array([[8.80701347e-01, 1.19189966e-01, 1.08687181e-04],
       [9.92408247e-01, 9.04959183e-04, 6.68679417e-03],
       [4.20100661e-02, 1.14195199e-01, 8.43794734e-01],
       [3.51190270e-02, 7.05384513e-01, 2.59496460e-01],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [271]:
special.softmax(x_in, axis=1)

array([[8.80701347e-01, 1.19189966e-01, 1.08687181e-04],
       [9.92408247e-01, 9.04959183e-04, 6.68679417e-03],
       [4.20100661e-02, 1.14195199e-01, 8.43794734e-01],
       [3.51190270e-02, 7.05384513e-01, 2.59496460e-01],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [272]:
x_in

array([[9, 7, 0],
       [8, 1, 3],
       [2, 3, 5],
       [5, 8, 7],
       [4, 3, 4]])

In [273]:
s = smax(x_in)
s

array([[8.80701347e-01, 1.19189966e-01, 1.08687181e-04],
       [9.92408247e-01, 9.04959183e-04, 6.68679417e-03],
       [4.20100661e-02, 1.14195199e-01, 8.43794734e-01],
       [3.51190270e-02, 7.05384513e-01, 2.59496460e-01],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [274]:
w = s[0].copy()
w

array([8.80701347e-01, 1.19189966e-01, 1.08687181e-04])

In [275]:
I = np.eye(3)

In [276]:
I 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [277]:
I - w

array([[ 1.19298653e-01, -1.19189966e-01, -1.08687181e-04],
       [-8.80701347e-01,  8.80810034e-01, -1.08687181e-04],
       [-8.80701347e-01, -1.19189966e-01,  9.99891313e-01]])

In [278]:
w[:, None]

array([[8.80701347e-01],
       [1.19189966e-01],
       [1.08687181e-04]])

In [279]:
w[:, None] * (I - w)

array([[ 1.05066485e-01, -1.04970764e-01, -9.57209464e-05],
       [-1.04970764e-01,  1.04983718e-01, -1.29544214e-05],
       [-9.57209464e-05, -1.29544214e-05,  1.08675368e-04]])

# Example derivative of Softmax:

In [280]:
x_in

array([[9, 7, 0],
       [8, 1, 3],
       [2, 3, 5],
       [5, 8, 7],
       [4, 3, 4]])

In [281]:
x_in[:, None, :]

array([[[9, 7, 0]],

       [[8, 1, 3]],

       [[2, 3, 5]],

       [[5, 8, 7]],

       [[4, 3, 4]]])

In [282]:
s = smax(x_in)
s

array([[8.80701347e-01, 1.19189966e-01, 1.08687181e-04],
       [9.92408247e-01, 9.04959183e-04, 6.68679417e-03],
       [4.20100661e-02, 1.14195199e-01, 8.43794734e-01],
       [3.51190270e-02, 7.05384513e-01, 2.59496460e-01],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [283]:
s[:, None, :]

array([[[8.80701347e-01, 1.19189966e-01, 1.08687181e-04]],

       [[9.92408247e-01, 9.04959183e-04, 6.68679417e-03]],

       [[4.20100661e-02, 1.14195199e-01, 8.43794734e-01]],

       [[3.51190270e-02, 7.05384513e-01, 2.59496460e-01]],

       [[4.22318798e-01, 1.55362403e-01, 4.22318798e-01]]])

In [284]:
np.eye(3) - s[:, None, :]

array([[[ 1.19298653e-01, -1.19189966e-01, -1.08687181e-04],
        [-8.80701347e-01,  8.80810034e-01, -1.08687181e-04],
        [-8.80701347e-01, -1.19189966e-01,  9.99891313e-01]],

       [[ 7.59175335e-03, -9.04959183e-04, -6.68679417e-03],
        [-9.92408247e-01,  9.99095041e-01, -6.68679417e-03],
        [-9.92408247e-01, -9.04959183e-04,  9.93313206e-01]],

       [[ 9.57989934e-01, -1.14195199e-01, -8.43794734e-01],
        [-4.20100661e-02,  8.85804801e-01, -8.43794734e-01],
        [-4.20100661e-02, -1.14195199e-01,  1.56205266e-01]],

       [[ 9.64880973e-01, -7.05384513e-01, -2.59496460e-01],
        [-3.51190270e-02,  2.94615487e-01, -2.59496460e-01],
        [-3.51190270e-02, -7.05384513e-01,  7.40503540e-01]],

       [[ 5.77681202e-01, -1.55362403e-01, -4.22318798e-01],
        [-4.22318798e-01,  8.44637597e-01, -4.22318798e-01],
        [-4.22318798e-01, -1.55362403e-01,  5.77681202e-01]]])

In [285]:
s[:, :, None]

array([[[8.80701347e-01],
        [1.19189966e-01],
        [1.08687181e-04]],

       [[9.92408247e-01],
        [9.04959183e-04],
        [6.68679417e-03]],

       [[4.20100661e-02],
        [1.14195199e-01],
        [8.43794734e-01]],

       [[3.51190270e-02],
        [7.05384513e-01],
        [2.59496460e-01]],

       [[4.22318798e-01],
        [1.55362403e-01],
        [4.22318798e-01]]])

In [286]:
dsdx = s[:, :, None] * (np.eye(3) - s[:, None, :]) #dxT = dx
dsdx

array([[[ 1.05066485e-01, -1.04970764e-01, -9.57209464e-05],
        [-1.04970764e-01,  1.04983718e-01, -1.29544214e-05],
        [-9.57209464e-05, -1.29544214e-05,  1.08675368e-04]],

       [[ 7.53411863e-03, -8.98088956e-04, -6.63602968e-03],
        [-8.98088956e-04,  9.04140231e-04, -6.05127578e-06],
        [-6.63602968e-03, -6.05127578e-06,  6.64208095e-03]],

       [[ 4.02452205e-02, -4.79734788e-03, -3.54478726e-02],
        [-4.79734788e-03,  1.01154656e-01, -9.63573079e-02],
        [-3.54478726e-02, -9.63573079e-02,  1.31805181e-01]],

       [[ 3.38856809e-02, -2.47724177e-02, -9.11326319e-03],
        [-2.47724177e-02,  2.07817202e-01, -1.83044784e-01],
        [-9.11326319e-03, -1.83044784e-01,  1.92158047e-01]],

       [[ 2.43965631e-01, -6.56124635e-02, -1.78353167e-01],
        [-6.56124635e-02,  1.31224927e-01, -6.56124635e-02],
        [-1.78353167e-01, -6.56124635e-02,  2.43965631e-01]]])

In [287]:
dsdx.shape

(5, 3, 3)

In [288]:
dLdsT = np.random.randint(0, 10, (5, 1, 3))
dLdsT

array([[[1, 4, 2]],

       [[4, 3, 5]],

       [[2, 4, 4]],

       [[0, 9, 6]],

       [[1, 0, 2]]])

In [289]:
dLdsT.shape

(5, 1, 3)

In [290]:
dsdx.shape

(5, 3, 3)

In [291]:
dLdx = np.matmul(dLdsT, dsdx)
dLdx

array([[[-3.15008012e-01,  3.14938200e-01,  6.98121036e-05]],

       [[-5.73794072e-03, -9.10191507e-04,  6.64813223e-03]],

       [[-8.04904410e-02,  9.59469576e-03,  7.08957452e-02]],

       [[-2.77631339e-01,  7.72086112e-01, -4.94454774e-01]],

       [[-1.12740704e-01, -1.96837391e-01,  3.09578094e-01]]])

In [292]:
np.squeeze(dLdx)

array([[-3.15008012e-01,  3.14938200e-01,  6.98121036e-05],
       [-5.73794072e-03, -9.10191507e-04,  6.64813223e-03],
       [-8.04904410e-02,  9.59469576e-03,  7.08957452e-02],
       [-2.77631339e-01,  7.72086112e-01, -4.94454774e-01],
       [-1.12740704e-01, -1.96837391e-01,  3.09578094e-01]])

### From notebook

In [293]:
s

array([[8.80701347e-01, 1.19189966e-01, 1.08687181e-04],
       [9.92408247e-01, 9.04959183e-04, 6.68679417e-03],
       [4.20100661e-02, 1.14195199e-01, 8.43794734e-01],
       [3.51190270e-02, 7.05384513e-01, 2.59496460e-01],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [294]:
batch_size, n_feats = s.shape

In [295]:
batch_size

5

In [296]:
n_feats

3

In [297]:
a = s.reshape(batch_size, n_feats, -1)

In [298]:
a

array([[[8.80701347e-01],
        [1.19189966e-01],
        [1.08687181e-04]],

       [[9.92408247e-01],
        [9.04959183e-04],
        [6.68679417e-03]],

       [[4.20100661e-02],
        [1.14195199e-01],
        [8.43794734e-01]],

       [[3.51190270e-02],
        [7.05384513e-01],
        [2.59496460e-01]],

       [[4.22318798e-01],
        [1.55362403e-01],
        [4.22318798e-01]]])

In [299]:
b = s.reshape(batch_size, -1, n_feats)
b

array([[[8.80701347e-01, 1.19189966e-01, 1.08687181e-04]],

       [[9.92408247e-01, 9.04959183e-04, 6.68679417e-03]],

       [[4.20100661e-02, 1.14195199e-01, 8.43794734e-01]],

       [[3.51190270e-02, 7.05384513e-01, 2.59496460e-01]],

       [[4.22318798e-01, 1.55362403e-01, 4.22318798e-01]]])

In [300]:
gradOutput = np.random.random((n_batch, n_feats))
gradOutput

array([[0.31666201, 0.69012764, 0.70102517],
       [0.15054726, 0.61437627, 0.27794916],
       [0.70692656, 0.88568222, 0.3556531 ],
       [0.68766159, 0.13238989, 0.70319304],
       [0.9725075 , 0.76373911, 0.17317561]])

In [301]:
gradOutput = dLdsT.copy()

In [302]:
gradOutput.shape

(5, 1, 3)

In [303]:
dLdsT.shape

(5, 1, 3)

In [304]:
np.multiply(np.eye(n_feats), a)

array([[[8.80701347e-01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.19189966e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.08687181e-04]],

       [[9.92408247e-01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 9.04959183e-04, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 6.68679417e-03]],

       [[4.20100661e-02, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.14195199e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 8.43794734e-01]],

       [[3.51190270e-02, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 7.05384513e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 2.59496460e-01]],

       [[4.22318798e-01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.55362403e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 4.22318798e-01]]])

In [305]:
np.multiply(a, b)

array([[[7.75634862e-01, 1.04970764e-01, 9.57209464e-05],
        [1.04970764e-01, 1.42062480e-02, 1.29544214e-05],
        [9.57209464e-05, 1.29544214e-05, 1.18129032e-08]],

       [[9.84874128e-01, 8.98088956e-04, 6.63602968e-03],
        [8.98088956e-04, 8.18951122e-07, 6.05127578e-06],
        [6.63602968e-03, 6.05127578e-06, 4.47132162e-05]],

       [[1.76484566e-03, 4.79734788e-03, 3.54478726e-02],
        [4.79734788e-03, 1.30405436e-02, 9.63573079e-02],
        [3.54478726e-02, 9.63573079e-02, 7.11989554e-01]],

       [[1.23334605e-03, 2.47724177e-02, 9.11326319e-03],
        [2.47724177e-02, 4.97567311e-01, 1.83044784e-01],
        [9.11326319e-03, 1.83044784e-01, 6.73384129e-02]],

       [[1.78353167e-01, 6.56124635e-02, 1.78353167e-01],
        [6.56124635e-02, 2.41374764e-02, 6.56124635e-02],
        [1.78353167e-01, 6.56124635e-02, 1.78353167e-01]]])

In [306]:
np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))

array([[[ 1.05066485e-01, -1.04970764e-01, -9.57209464e-05],
        [-1.04970764e-01,  1.04983718e-01, -1.29544214e-05],
        [-9.57209464e-05, -1.29544214e-05,  1.08675368e-04]],

       [[ 7.53411863e-03, -8.98088956e-04, -6.63602968e-03],
        [-8.98088956e-04,  9.04140231e-04, -6.05127578e-06],
        [-6.63602968e-03, -6.05127578e-06,  6.64208095e-03]],

       [[ 4.02452205e-02, -4.79734788e-03, -3.54478726e-02],
        [-4.79734788e-03,  1.01154656e-01, -9.63573079e-02],
        [-3.54478726e-02, -9.63573079e-02,  1.31805181e-01]],

       [[ 3.38856809e-02, -2.47724177e-02, -9.11326319e-03],
        [-2.47724177e-02,  2.07817202e-01, -1.83044784e-01],
        [-9.11326319e-03, -1.83044784e-01,  1.92158047e-01]],

       [[ 2.43965631e-01, -6.56124635e-02, -1.78353167e-01],
        [-6.56124635e-02,  1.31224927e-01, -6.56124635e-02],
        [-1.78353167e-01, -6.56124635e-02,  2.43965631e-01]]])

In [307]:
dsdx

array([[[ 1.05066485e-01, -1.04970764e-01, -9.57209464e-05],
        [-1.04970764e-01,  1.04983718e-01, -1.29544214e-05],
        [-9.57209464e-05, -1.29544214e-05,  1.08675368e-04]],

       [[ 7.53411863e-03, -8.98088956e-04, -6.63602968e-03],
        [-8.98088956e-04,  9.04140231e-04, -6.05127578e-06],
        [-6.63602968e-03, -6.05127578e-06,  6.64208095e-03]],

       [[ 4.02452205e-02, -4.79734788e-03, -3.54478726e-02],
        [-4.79734788e-03,  1.01154656e-01, -9.63573079e-02],
        [-3.54478726e-02, -9.63573079e-02,  1.31805181e-01]],

       [[ 3.38856809e-02, -2.47724177e-02, -9.11326319e-03],
        [-2.47724177e-02,  2.07817202e-01, -1.83044784e-01],
        [-9.11326319e-03, -1.83044784e-01,  1.92158047e-01]],

       [[ 2.43965631e-01, -6.56124635e-02, -1.78353167e-01],
        [-6.56124635e-02,  1.31224927e-01, -6.56124635e-02],
        [-1.78353167e-01, -6.56124635e-02,  2.43965631e-01]]])

In [308]:
np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b)))

array([[[ 1.05066485e-01, -4.19883055e-01, -1.91441893e-04],
        [-1.04970764e-01,  4.19934873e-01, -2.59088428e-05],
        [-9.57209464e-05, -5.18176855e-05,  2.17350735e-04]],

       [[ 3.01364745e-02, -2.69426687e-03, -3.31801484e-02],
        [-3.59235582e-03,  2.71242069e-03, -3.02563789e-05],
        [-2.65441187e-02, -1.81538274e-05,  3.32104048e-02]],

       [[ 8.04904410e-02, -1.91893915e-02, -1.41791490e-01],
        [-9.59469576e-03,  4.04618623e-01, -3.85429232e-01],
        [-7.08957452e-02, -3.85429232e-01,  5.27220722e-01]],

       [[ 0.00000000e+00, -2.22951759e-01, -5.46795791e-02],
        [-0.00000000e+00,  1.87035482e+00, -1.09826871e+00],
        [-0.00000000e+00, -1.64740306e+00,  1.15294828e+00]],

       [[ 2.43965631e-01, -0.00000000e+00, -3.56706335e-01],
        [-6.56124635e-02,  0.00000000e+00, -1.31224927e-01],
        [-1.78353167e-01, -0.00000000e+00,  4.87931262e-01]]])

In [309]:
note_res = np.multiply(gradOutput.reshape(batch_size, -1, n_feats), np.subtract(np.multiply(np.eye(n_feats), a), np.multiply(a, b))).sum(axis=2)

In [310]:
my_res = np.squeeze(np.matmul(dLdsT, dsdx))

In [311]:
np.allclose(note_res, my_res)

True

In [312]:
note_res

array([[-3.15008012e-01,  3.14938200e-01,  6.98121036e-05],
       [-5.73794072e-03, -9.10191507e-04,  6.64813223e-03],
       [-8.04904410e-02,  9.59469576e-03,  7.08957452e-02],
       [-2.77631339e-01,  7.72086112e-01, -4.94454774e-01],
       [-1.12740704e-01, -1.96837391e-01,  3.09578094e-01]])

In [313]:
my_res

array([[-3.15008012e-01,  3.14938200e-01,  6.98121036e-05],
       [-5.73794072e-03, -9.10191507e-04,  6.64813223e-03],
       [-8.04904410e-02,  9.59469576e-03,  7.08957452e-02],
       [-2.77631339e-01,  7.72086112e-01, -4.94454774e-01],
       [-1.12740704e-01, -1.96837391e-01,  3.09578094e-01]])

---

# Example derivative of LogSoftMax

In [314]:
x_in = np.array([[6, 2, 8],
       [9, 6, 3],
       [9, 9, 4],
       [6, 7, 0],
       [9, 8, 9]])

In [315]:
s = smax(x_in)
s

array([[1.18943236e-01, 2.17852136e-03, 8.78878243e-01],
       [9.50330212e-01, 4.73141552e-02, 2.35563308e-03],
       [4.98321169e-01, 4.98321169e-01, 3.35766163e-03],
       [2.68762254e-01, 7.30571551e-01, 6.66195022e-04],
       [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]])

In [316]:
s[:,None,:]

array([[[1.18943236e-01, 2.17852136e-03, 8.78878243e-01]],

       [[9.50330212e-01, 4.73141552e-02, 2.35563308e-03]],

       [[4.98321169e-01, 4.98321169e-01, 3.35766163e-03]],

       [[2.68762254e-01, 7.30571551e-01, 6.66195022e-04]],

       [[4.22318798e-01, 1.55362403e-01, 4.22318798e-01]]])

In [317]:
res2 = s[:,None,:] * np.ones(3)[:,None]
res2

array([[[1.18943236e-01, 2.17852136e-03, 8.78878243e-01],
        [1.18943236e-01, 2.17852136e-03, 8.78878243e-01],
        [1.18943236e-01, 2.17852136e-03, 8.78878243e-01]],

       [[9.50330212e-01, 4.73141552e-02, 2.35563308e-03],
        [9.50330212e-01, 4.73141552e-02, 2.35563308e-03],
        [9.50330212e-01, 4.73141552e-02, 2.35563308e-03]],

       [[4.98321169e-01, 4.98321169e-01, 3.35766163e-03],
        [4.98321169e-01, 4.98321169e-01, 3.35766163e-03],
        [4.98321169e-01, 4.98321169e-01, 3.35766163e-03]],

       [[2.68762254e-01, 7.30571551e-01, 6.66195022e-04],
        [2.68762254e-01, 7.30571551e-01, 6.66195022e-04],
        [2.68762254e-01, 7.30571551e-01, 6.66195022e-04]],

       [[4.22318798e-01, 1.55362403e-01, 4.22318798e-01],
        [4.22318798e-01, 1.55362403e-01, 4.22318798e-01],
        [4.22318798e-01, 1.55362403e-01, 4.22318798e-01]]])

In [318]:
dldx = np.eye(3) - res2
dldx

array([[[ 8.81056764e-01, -2.17852136e-03, -8.78878243e-01],
        [-1.18943236e-01,  9.97821479e-01, -8.78878243e-01],
        [-1.18943236e-01, -2.17852136e-03,  1.21121757e-01]],

       [[ 4.96697883e-02, -4.73141552e-02, -2.35563308e-03],
        [-9.50330212e-01,  9.52685845e-01, -2.35563308e-03],
        [-9.50330212e-01, -4.73141552e-02,  9.97644367e-01]],

       [[ 5.01678831e-01, -4.98321169e-01, -3.35766163e-03],
        [-4.98321169e-01,  5.01678831e-01, -3.35766163e-03],
        [-4.98321169e-01, -4.98321169e-01,  9.96642338e-01]],

       [[ 7.31237746e-01, -7.30571551e-01, -6.66195022e-04],
        [-2.68762254e-01,  2.69428449e-01, -6.66195022e-04],
        [-2.68762254e-01, -7.30571551e-01,  9.99333805e-01]],

       [[ 5.77681202e-01, -1.55362403e-01, -4.22318798e-01],
        [-4.22318798e-01,  8.44637597e-01, -4.22318798e-01],
        [-4.22318798e-01, -1.55362403e-01,  5.77681202e-01]]])

In [319]:
dLdlT = np.array([[0.9641629 , 0.13632945, 0.56112404],
       [0.91547089, 0.95909897, 0.27756155],
       [0.96150247, 0.87256632, 0.81025121],
       [0.83971777, 0.12481911, 0.99006227],
       [0.780089  , 0.28662484, 0.68290024]])

In [320]:
dLdlT

array([[0.9641629 , 0.13632945, 0.56112404],
       [0.91547089, 0.95909897, 0.27756155],
       [0.96150247, 0.87256632, 0.81025121],
       [0.83971777, 0.12481911, 0.99006227],
       [0.780089  , 0.28662484, 0.68290024]])

In [321]:
dLdlT[:,None,:]

array([[[0.9641629 , 0.13632945, 0.56112404]],

       [[0.91547089, 0.95909897, 0.27756155]],

       [[0.96150247, 0.87256632, 0.81025121]],

       [[0.83971777, 0.12481911, 0.99006227]],

       [[0.780089  , 0.28662484, 0.68290024]]])

In [322]:
dldx.shape

(5, 3, 3)

In [323]:
dLdlT.shape

(5, 3)

In [324]:
dLdxT = np.squeeze(np.matmul(dLdlT[:,None,:], dldx))
dLdxT

array([[ 0.76652487,  0.13270958, -0.89923445],
       [-1.12976461,  0.85727269,  0.27249192],
       [-0.35621816, -0.44515431,  0.80137248],
       [ 0.3143953 , -1.30315542,  0.98876013],
       [ 0.04119408,  0.01480059, -0.05599468]])

In [325]:
def updateOutput(input):
        # start with normalization for numerical stability
        output = np.subtract(input, input.max(axis=1, keepdims=True))
        
        # Your code goes here. ################################################
        output = output - np.log(np.sum(np.exp(output), axis=1, keepdims=True))
        return output
    
def updateGradInput(input, gradOutput):
        # Your code goes here. ################################################
        local_derivative = np.zeros((gradOutput.shape[0], gradOutput.shape[1], gradOutput.shape[1]))
        local_derivative[:, np.arange(gradOutput.shape[1]), np.arange(gradOutput.shape[1])] = 1.
        local_softmax = np.exp(input)
        local_softmax = np.exp(output)
        local_softmax = local_softmax/local_softmax.sum(axis=1, keepdims=True)
        local_derivative = local_derivative - local_softmax[:, None, :]
        
        gradInput = np.matmul(gradOutput[:, None, :], (local_derivative))[:, 0, :]

        return gradInput

In [326]:
output = updateOutput(x_in)

In [327]:
output

array([[-2.12910891, -6.12910891, -0.12910891],
       [-0.05094576, -3.05094576, -6.05094576],
       [-0.69651049, -0.69651049, -5.69651049],
       [-1.3139281 , -0.3139281 , -7.3139281 ],
       [-0.8619948 , -1.8619948 , -0.8619948 ]])

In [328]:
special.log_softmax(x_in, axis=1)

array([[-2.12910891, -6.12910891, -0.12910891],
       [-0.05094576, -3.05094576, -6.05094576],
       [-0.69651049, -0.69651049, -5.69651049],
       [-1.3139281 , -0.3139281 , -7.3139281 ],
       [-0.8619948 , -1.8619948 , -0.8619948 ]])

In [329]:
local_derivative = np.zeros((dLdlT.shape[0], dLdlT.shape[1], dLdlT.shape[1]))
local_derivative[:, np.arange(dLdlT.shape[1]), np.arange(dLdlT.shape[1])] = 1.
local_softmax1 = np.exp(x_in)
local_softmax2 = np.exp(output)
local_softmax1 = local_softmax1/local_softmax1.sum(axis=1, keepdims=True)
local_softmax2 = local_softmax2/local_softmax2.sum(axis=1, keepdims=True)
local_derivative = local_derivative - local_softmax2[:, None, :]
gradInput = np.matmul(dLdlT[:, None, :], (local_derivative))[:, 0, :]

In [330]:
local_derivative

array([[[ 8.81056764e-01, -2.17852136e-03, -8.78878243e-01],
        [-1.18943236e-01,  9.97821479e-01, -8.78878243e-01],
        [-1.18943236e-01, -2.17852136e-03,  1.21121757e-01]],

       [[ 4.96697883e-02, -4.73141552e-02, -2.35563308e-03],
        [-9.50330212e-01,  9.52685845e-01, -2.35563308e-03],
        [-9.50330212e-01, -4.73141552e-02,  9.97644367e-01]],

       [[ 5.01678831e-01, -4.98321169e-01, -3.35766163e-03],
        [-4.98321169e-01,  5.01678831e-01, -3.35766163e-03],
        [-4.98321169e-01, -4.98321169e-01,  9.96642338e-01]],

       [[ 7.31237746e-01, -7.30571551e-01, -6.66195022e-04],
        [-2.68762254e-01,  2.69428449e-01, -6.66195022e-04],
        [-2.68762254e-01, -7.30571551e-01,  9.99333805e-01]],

       [[ 5.77681202e-01, -1.55362403e-01, -4.22318798e-01],
        [-4.22318798e-01,  8.44637597e-01, -4.22318798e-01],
        [-4.22318798e-01, -1.55362403e-01,  5.77681202e-01]]])

In [331]:
dldx

array([[[ 8.81056764e-01, -2.17852136e-03, -8.78878243e-01],
        [-1.18943236e-01,  9.97821479e-01, -8.78878243e-01],
        [-1.18943236e-01, -2.17852136e-03,  1.21121757e-01]],

       [[ 4.96697883e-02, -4.73141552e-02, -2.35563308e-03],
        [-9.50330212e-01,  9.52685845e-01, -2.35563308e-03],
        [-9.50330212e-01, -4.73141552e-02,  9.97644367e-01]],

       [[ 5.01678831e-01, -4.98321169e-01, -3.35766163e-03],
        [-4.98321169e-01,  5.01678831e-01, -3.35766163e-03],
        [-4.98321169e-01, -4.98321169e-01,  9.96642338e-01]],

       [[ 7.31237746e-01, -7.30571551e-01, -6.66195022e-04],
        [-2.68762254e-01,  2.69428449e-01, -6.66195022e-04],
        [-2.68762254e-01, -7.30571551e-01,  9.99333805e-01]],

       [[ 5.77681202e-01, -1.55362403e-01, -4.22318798e-01],
        [-4.22318798e-01,  8.44637597e-01, -4.22318798e-01],
        [-4.22318798e-01, -1.55362403e-01,  5.77681202e-01]]])

In [332]:
gradInput

array([[ 0.76652487,  0.13270958, -0.89923445],
       [-1.12976461,  0.85727269,  0.27249192],
       [-0.35621816, -0.44515431,  0.80137248],
       [ 0.3143953 , -1.30315542,  0.98876013],
       [ 0.04119408,  0.01480059, -0.05599468]])

In [333]:
np.allclose(gradInput, dLdxT)

True

----


### Leaky RELU

In [334]:
x_in = np.array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [335]:
x_in

array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [336]:
np.where(x_in >= 0.5, x_in, 0.05*x_in)

array([[9.91645587e-01, 7.21258379e-01, 4.37775540e-03],
       [1.10883019e-02, 1.51194938e-04, 1.54989067e-02],
       [8.99964070e-03, 9.28676271e-01, 8.45949432e-01],
       [1.69402628e-05, 2.43723392e-02, 8.94100048e-01],
       [8.18831945e-03, 6.04098247e-01, 4.43218693e-03]])

In [337]:
np.where(x_in >= 0.5, x_in, 0.05*x_in)/ x_in

array([[1.  , 1.  , 0.05],
       [0.05, 0.05, 0.05],
       [0.05, 1.  , 1.  ],
       [0.05, 0.05, 1.  ],
       [0.05, 1.  , 0.05]])

In [338]:
a = np.where(x_in >= 0.5, x_in, -1)

In [339]:
a

array([[ 0.99164559,  0.72125838, -1.        ],
       [-1.        , -1.        , -1.        ],
       [-1.        ,  0.92867627,  0.84594943],
       [-1.        , -1.        ,  0.89410005],
       [-1.        ,  0.60409825, -1.        ]])

In [340]:
a[:, :, None]

array([[[ 0.99164559],
        [ 0.72125838],
        [-1.        ]],

       [[-1.        ],
        [-1.        ],
        [-1.        ]],

       [[-1.        ],
        [ 0.92867627],
        [ 0.84594943]],

       [[-1.        ],
        [-1.        ],
        [ 0.89410005]],

       [[-1.        ],
        [ 0.60409825],
        [-1.        ]]])

In [341]:
dLeakdx = np.eye(3) * a[:, :, None]

In [342]:
dLeakdx

array([[[ 0.99164559,  0.        ,  0.        ],
        [ 0.        ,  0.72125838,  0.        ],
        [-0.        , -0.        , -1.        ]],

       [[-1.        , -0.        , -0.        ],
        [-0.        , -1.        , -0.        ],
        [-0.        , -0.        , -1.        ]],

       [[-1.        , -0.        , -0.        ],
        [ 0.        ,  0.92867627,  0.        ],
        [ 0.        ,  0.        ,  0.84594943]],

       [[-1.        , -0.        , -0.        ],
        [-0.        , -1.        , -0.        ],
        [ 0.        ,  0.        ,  0.89410005]],

       [[-1.        , -0.        , -0.        ],
        [ 0.        ,  0.60409825,  0.        ],
        [-0.        , -0.        , -1.        ]]])

In [343]:
gradOutput = np.array([[[6, 3, 4]],

       [[3, 2, 2]],

       [[7, 5, 4]],

       [[3, 4, 2]],

       [[2, 5, 3]]])

In [344]:
np.squeeze(np.matmul(gradOutput, dLeakdx))

array([[ 5.94987352,  2.16377514, -4.        ],
       [-3.        , -2.        , -2.        ],
       [-7.        ,  4.64338136,  3.38379773],
       [-3.        , -4.        ,  1.7882001 ],
       [-2.        ,  3.02049124, -3.        ]])

In [345]:
np.matmul(gradOutput, dLeakdx)

array([[[ 5.94987352,  2.16377514, -4.        ]],

       [[-3.        , -2.        , -2.        ]],

       [[-7.        ,  4.64338136,  3.38379773]],

       [[-3.        , -4.        ,  1.7882001 ]],

       [[-2.        ,  3.02049124, -3.        ]]])

In [346]:
np.matmul(gradOutput, dLeakdx)[:,0,:]

array([[ 5.94987352,  2.16377514, -4.        ],
       [-3.        , -2.        , -2.        ],
       [-7.        ,  4.64338136,  3.38379773],
       [-3.        , -4.        ,  1.7882001 ],
       [-2.        ,  3.02049124, -3.        ]])

----

## ELU

In [347]:
x_in

array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [348]:
alpha = 0.5

In [349]:
elu = np.where(x_in >= 0.5, x_in, alpha*(np.exp(x_in) - 1))

In [350]:
elu

array([[9.91645587e-01, 7.21258379e-01, 4.57512066e-02],
       [1.24139646e-01, 1.51423768e-03, 1.81697651e-01],
       [9.86043800e-02, 9.28676271e-01, 8.45949432e-01],
       [1.69431328e-04, 3.14076939e-01, 8.94100048e-01],
       [8.89695517e-02, 6.04098247e-01, 4.63456516e-02]])

In [351]:
dELUdx = np.eye(3) * np.where(elu >= 0.5, 1.0, elu+alpha)[:,:,None]

In [352]:
dELUdx

array([[[1.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 0.        , 0.54575121]],

       [[0.62413965, 0.        , 0.        ],
        [0.        , 0.50151424, 0.        ],
        [0.        , 0.        , 0.68169765]],

       [[0.59860438, 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.50016943, 0.        , 0.        ],
        [0.        , 0.81407694, 0.        ],
        [0.        , 0.        , 1.        ]],

       [[0.58896955, 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 0.        , 0.54634565]]])

In [353]:
gradOutput

array([[[6, 3, 4]],

       [[3, 2, 2]],

       [[7, 5, 4]],

       [[3, 4, 2]],

       [[2, 5, 3]]])

In [354]:
4 * alpha * np.exp(8.75551079e-02)

2.1830048263828736

In [355]:
np.squeeze(np.matmul(gradOutput, dELUdx))

array([[6.        , 3.        , 2.18300483],
       [1.87241894, 1.00302848, 1.3633953 ],
       [4.19023066, 5.        , 4.        ],
       [1.50050829, 3.25630776, 2.        ],
       [1.1779391 , 5.        , 1.63903695]])

In [356]:
output = x_in.copy()

In [357]:
output[output < 0.5] = alpha * (np.exp(output[output < 0.5]) - 1)

In [358]:
x_in

array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [359]:
output

array([[9.91645587e-01, 7.21258379e-01, 4.57512066e-02],
       [1.24139646e-01, 1.51423768e-03, 1.81697651e-01],
       [9.86043800e-02, 9.28676271e-01, 8.45949432e-01],
       [1.69431328e-04, 3.14076939e-01, 8.94100048e-01],
       [8.89695517e-02, 6.04098247e-01, 4.63456516e-02]])

In [360]:
elu

array([[9.91645587e-01, 7.21258379e-01, 4.57512066e-02],
       [1.24139646e-01, 1.51423768e-03, 1.81697651e-01],
       [9.86043800e-02, 9.28676271e-01, 8.45949432e-01],
       [1.69431328e-04, 3.14076939e-01, 8.94100048e-01],
       [8.89695517e-02, 6.04098247e-01, 4.63456516e-02]])

In [361]:
np.allclose(output, elu)

True

In [362]:
gradInput = np.squeeze(gradOutput).astype(float)

In [363]:
gradInput

array([[6., 3., 4.],
       [3., 2., 2.],
       [7., 5., 4.],
       [3., 4., 2.],
       [2., 5., 3.]])

In [364]:
4 * (output[0][2] + alpha)

2.1830048263828736

In [365]:
gradInput[x_in < 0.5] *= (output[x_in < 0.5] + alpha)

In [366]:
gradInput

array([[6.        , 3.        , 2.18300483],
       [1.87241894, 1.00302848, 1.3633953 ],
       [4.19023066, 5.        , 4.        ],
       [1.50050829, 3.25630776, 2.        ],
       [1.1779391 , 5.        , 1.63903695]])

In [367]:
np.squeeze(np.matmul(gradOutput, dELUdx))

array([[6.        , 3.        , 2.18300483],
       [1.87241894, 1.00302848, 1.3633953 ],
       [4.19023066, 5.        , 4.        ],
       [1.50050829, 3.25630776, 2.        ],
       [1.1779391 , 5.        , 1.63903695]])

----

# Softplus

In [368]:
x_in

array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [369]:
s = np.exp(x_in) / (1 + np.exp(x_in))

In [370]:
s

array([[0.72941283, 0.67288406, 0.5218748 ],
       [0.5552154 , 0.50075597, 0.57687992],
       [0.54487711, 0.71680665, 0.69971675],
       [0.5000847 , 0.61950478, 0.70973555],
       [0.54085034, 0.64659336, 0.52214643]])

In [371]:
dSoftdx = np.eye(3) * s[:, :, None]
dSoftdx

array([[[0.72941283, 0.        , 0.        ],
        [0.        , 0.67288406, 0.        ],
        [0.        , 0.        , 0.5218748 ]],

       [[0.5552154 , 0.        , 0.        ],
        [0.        , 0.50075597, 0.        ],
        [0.        , 0.        , 0.57687992]],

       [[0.54487711, 0.        , 0.        ],
        [0.        , 0.71680665, 0.        ],
        [0.        , 0.        , 0.69971675]],

       [[0.5000847 , 0.        , 0.        ],
        [0.        , 0.61950478, 0.        ],
        [0.        , 0.        , 0.70973555]],

       [[0.54085034, 0.        , 0.        ],
        [0.        , 0.64659336, 0.        ],
        [0.        , 0.        , 0.52214643]]])

In [372]:
np.squeeze(np.matmul(gradOutput, dSoftdx))

array([[4.376477  , 2.01865218, 2.08749922],
       [1.66564621, 1.00151195, 1.15375985],
       [3.81413977, 3.58403326, 2.79886701],
       [1.5002541 , 2.4780191 , 1.41947111],
       [1.08170068, 3.2329668 , 1.5664393 ]])

In [373]:
np.matmul(np.squeeze(gradOutput), dSoftdx)

array([[[4.376477  , 2.01865218, 2.08749922],
        [2.1882385 , 1.34576812, 1.04374961],
        [5.10588984, 3.3644203 , 2.08749922],
        [2.1882385 , 2.69153624, 1.04374961],
        [1.45882567, 3.3644203 , 1.56562441]],

       [[3.33129242, 1.50226792, 2.3075197 ],
        [1.66564621, 1.00151195, 1.15375985],
        [3.88650782, 2.50377987, 2.3075197 ],
        [1.66564621, 2.0030239 , 1.15375985],
        [1.11043081, 2.50377987, 1.73063977]],

       [[3.26926266, 2.15041996, 2.79886701],
        [1.63463133, 1.4336133 , 1.39943351],
        [3.81413977, 3.58403326, 2.79886701],
        [1.63463133, 2.86722661, 1.39943351],
        [1.08975422, 3.58403326, 2.09915026]],

       [[3.00050821, 1.85851433, 2.83894221],
        [1.5002541 , 1.23900955, 1.41947111],
        [3.50059291, 3.09752388, 2.83894221],
        [1.5002541 , 2.4780191 , 1.41947111],
        [1.0001694 , 3.09752388, 2.12920666]],

       [[3.24510204, 1.93978008, 2.08858574],
        [1.62255102, 1.293

---

# Dropout

In [374]:
p = 0.5

In [375]:
np.ones_like(x_in)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [376]:
mask = np.random.binomial(1, 1 - p, x_in.shape)

In [377]:
mask

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [378]:
np.multiply(x_in, mask) / (1 - p)

array([[0.        , 1.44251676, 0.        ],
       [0.44353207, 0.0060478 , 0.61995627],
       [0.        , 1.85735254, 0.        ],
       [0.        , 0.        , 1.7882001 ],
       [0.32753278, 0.        , 0.        ]])

In [379]:
out = np.squeeze(gradOutput)

In [380]:
out

array([[6, 3, 4],
       [3, 2, 2],
       [7, 5, 4],
       [3, 4, 2],
       [2, 5, 3]])

In [381]:
np.multiply(out, mask) / (1-p)

array([[ 0.,  6.,  0.],
       [ 6.,  4.,  4.],
       [ 0., 10.,  0.],
       [ 0.,  0.,  4.],
       [ 4.,  0.,  0.]])

---

# Batch Normalization

In [382]:
x_in

array([[9.91645587e-01, 7.21258379e-01, 8.75551079e-02],
       [2.21766037e-01, 3.02389876e-03, 3.09978134e-01],
       [1.79992814e-01, 9.28676271e-01, 8.45949432e-01],
       [3.38805255e-04, 4.87446783e-01, 8.94100048e-01],
       [1.63766389e-01, 6.04098247e-01, 8.86437386e-02]])

In [383]:
x_mean = np.mean(x_in, axis=0, keepdims=True)
x_sqrt_var = np.sqrt(x_in.var(axis=0, keepdims=True) + 1e-3)

In [384]:
output = (x_in - x_mean) / x_sqrt_var
output

array([[ 1.94471143,  0.55412651, -0.9994321 ],
       [-0.25657875, -1.75498328, -0.37795373],
       [-0.37601949,  1.22097098,  1.11961859],
       [-0.88969803, -0.19757319,  1.25415757],
       [-0.42241515,  0.17745898, -0.99639033]])

In [385]:
gout = out.copy()
gout

array([[6, 3, 4],
       [3, 2, 2],
       [7, 5, 4],
       [3, 4, 2],
       [2, 5, 3]])

In [386]:
x_in.shape[0]

5

In [387]:
a = x_in.shape[0] * gout

In [388]:
a

array([[30, 15, 20],
       [15, 10, 10],
       [35, 25, 20],
       [15, 20, 10],
       [10, 25, 15]])

In [389]:
np.sum(gout, axis=0, keepdims=True)

array([[21, 19, 15]])

In [390]:
b = a - np.sum(gout, axis=0, keepdims=True)
b

array([[  9,  -4,   5],
       [ -6,  -9,  -5],
       [ 14,   6,   5],
       [ -6,   1,  -5],
       [-11,   6,   0]])

In [391]:
c = b - output * np.sum(gout * output, axis=0, keepdims=True)
c

array([[-0.24218556, -6.41281646,  4.24441199],
       [-4.78061682, -1.35832891, -5.28573958],
       [15.78702191,  0.68356268,  5.84645108],
       [-1.77173548,  1.86028702, -4.05183512],
       [-8.99248404,  5.22729567, -0.75328837]])

In [392]:
1/(x_in.shape[0] * np.sqrt(x_in.var(axis=0, keepdims=True) + 1e-3)) * c

array([[-0.13849457, -4.12341589,  2.37188595],
       [-2.73381072, -0.87340018, -2.95380642],
       [ 9.02785799,  0.43952813,  3.26714635],
       [-1.01317249,  1.19615727, -2.26426906],
       [-5.1423802 ,  3.36113066, -0.4209568 ]])

----

My:

In [393]:
a = 1/x_sqrt_var

In [394]:
second = np.mean(gout, axis=0, keepdims=True)

In [395]:
third = np.mean(gout * output, axis=0, keepdims=True) * output

In [396]:
a * (gout - second - third)

array([[-0.13849457, -4.12341589,  2.37188595],
       [-2.73381072, -0.87340018, -2.95380642],
       [ 9.02785799,  0.43952813,  3.26714635],
       [-1.01317249,  1.19615727, -2.26426906],
       [-5.1423802 ,  3.36113066, -0.4209568 ]])

---

module style:

In [397]:
gradInput = gout.copy().astype(float)

In [398]:
gradInput -= np.mean(gout.astype(float), axis=0, keepdims=True)

In [399]:
gradInput -= np.mean(gout * output, axis=0, keepdims=True) * output

In [400]:
gradInput *= 1/x_sqrt_var

In [401]:
gradInput

array([[-0.13849457, -4.12341589,  2.37188595],
       [-2.73381072, -0.87340018, -2.95380642],
       [ 9.02785799,  0.43952813,  3.26714635],
       [-1.01317249,  1.19615727, -2.26426906],
       [-5.1423802 ,  3.36113066, -0.4209568 ]])

----

# Training MNIST

In [402]:
def one_hot_encode(input, classes=10):
    one_hot_targets = np.eye(classes)[input]
    return one_hot_targets

In [414]:
np.eye(10)[np.random.binomial(10, 0.3, 5).reshape(1, -1)]

array([[[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]])

In [412]:
np.random.binomial(10, 0.3, 5).reshape(1, -1)

array([[3, 2, 0, 3, 5]])